### ISSUE TITLE
Issue with the setting frameworks: ['mocha', 'requirejs', 'sinon-chai'] in karma.conf.js when using karma-sinon-chai with RequireJs

### ISSUE THREAD

**Issue by oredi** [kmees/karma-sinon-chai#11]
While working on a project that is using RequireJs, I found that to get Karma runner to work with karma-sinon-chai. The setting in karma.conf.js needs to read frameworks: ['mocha', 'requirejs', 'sinon-chai']. It appears to be a problem not being able to set the properties below if 'requirejs' is not set before 'sinon-chai':

1. window.chai.should()
2. window.chai.expect
3. window.chai.expect

Is that the correct setting for using karma-sinon-chai with RequireJs

**Comment by kmees** [comment]
Currently there is no support for RequireJS. Have a look at [karma-chai-plugins](https://www.npmjs.com/package/karma-chai-plugins) instead.
