### ISSUE TITLE
RangeError: Maximum call stack size exceeded in version 0.3.0 

### ISSUE THREAD

**Issue by kirill-konshin** [kmees/karma-sinon-chai#13]
```
PhantomJS 1.9.8 (Mac OS X) ERROR
  RangeError: Maximum call stack size exceeded.
  at /Users/dis/JEDI/amarosa_mod/src/app/node_modules/karma-sinon-chai/node_modules/chai/chai.js:3421
```

When I roll back to 0.2.x everything works well.

**Comment by kirill-konshin** [comment]
Bump!!! 2 weeks -- no response...

**Comment by kmees** [comment]
Sorry, I was on vacation. `0.3.0` updated chai from `1.9` to `1.10`, maybe that is the issue but i cannot reproduce the error without additional informations.

**Comment by kirill-konshin** [comment]
Previous error seems to be fixed, but here is the new one:

```
Error: Mismatched anonymous define() module: function () {
              return sinonChai;
          }
```

Code is located in `sinon-chai.js` file.

**Comment by kirill-konshin** [comment]
```js
        define('sinon-chai', [], function () { // added 'sinon-chai', []
            return sinonChai;
        });
```

Looks like this fixes the issue... Just give the module a name.

**Comment by kirill-konshin** [comment]
I am using karma-requirejs plugin, by the way. The file which produces the error `sinon-chai.js` from `sinon-chai` package.

**Comment by kmees** [comment]
I have no experience with requirejs / karma but I'll keep an eye on the other issue and see if they find a fix

**Comment by kirill-konshin** [comment]
https://github.com/princed/karma-chai-plugins/pull/21#issuecomment-89001973 Look at this PR for another similar package.

**Comment by jenifersilva** [comment]
Same until today using version `3.5.0`

**Comment by bendialpad** [comment]
This is still happening on the latest version.
