### ISSUE TITLE
Instead of including your own copy of sinon and chai, can you simply use the ones already installed by the user?

### ISSUE THREAD

**Issue by jack4it** [kmees/karma-sinon-chai#14]
For example, there is already a karma-chai plugin, a karma-sinon plugin which both work well. And neither of them includes their own copy of the respective package.

If this is a plugin which intends to auto load "sinon-chai", then you should just add the entry of snon-chai to the files array and that's it. This also would save you a lot of efforts of keeping track of the dependencies updates.

Thoughts?

**Comment by amercier** [comment]
Alternatively, [karma-chai-sinon](https://www.npmjs.com/package/karma-chai-sinon) uses `peerDependencies` instead of `dependencies`, which allows you to use whatever version of Chai and Sinon you want.
