### ISSUE TITLE
Getting 'Mismatched anonymous define()'

### ISSUE THREAD

**Issue by fmayer-tstllc** [kmees/karma-sinon-chai#15]
I replaced karma-chai with karma-sinon-chai in my working karma/mocha/chai Grunt configuration, and now I get:

    Uncaught Error: Mismatched anonymous define() module: function () {
              return sinonChai;
          }

My Karma configuration has
     frameworks: ['mocha', 'requirejs', 'chai-datetime', 'sinon-chai']

This looks similar to an old Chai issue: https://github.com/princed/karma-chai-plugins/issues/3

**Comment by onikiienko** [comment]
some issue

**Comment by MartijnR** [comment]
Experienced the same with 0.3.0. Rolling back to v.0.2.x resolves it.

**Comment by loganweiluo** [comment]
Still having the same issue with v1.1.0

Error message is:
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  Error: Mismatched anonymous define() module: function () {
              return sinonChai;
          }
  http://requirejs.org/docs/errors.html#mismatch
  at /Users/wwluo/work/ctp-mobile/node_modules/requirejs/require.js:140

karma config is: 
frameworks: ['mocha', 'requirejs', 'sinon-chai']

rolling back to v0.2.0 fixes the issue.
