### ISSUE TITLE
breaking changes changelog?

### ISSUE THREAD

**Issue by janusch** [kmees/karma-sinon-chai#19]
Hey,
I really like this module, great work!

When I tried to upgrade to 3.0.0 a few tests broke. I was just wondering if there is a changelog somewhere mentioning the breaking changes?
Why are there breaking changes, is it because Sinon or Chai released new major version? If so, maybe I can find a document describing the breaking changes there?

Cheers.

**Comment by janusch** [comment]
just a short update on the breaking change I experienced.

before 1.0 the sinon.fakeServer was present and just worked.
In 1.0 the fakeServer is all of a sudden undefined.

Is this the intended behavior?

Would appreciate a short comment on this issue

**Comment by vitalets** [comment]
also fakeTimers is disappeared

**Comment by kmees** [comment]
Added Changelog to README, the breaking changes were due to broken sinon version
