### ISSUE TITLE
Getting Chai is not defined errors

### ISSUE THREAD

**Issue by omerts** [kmees/karma-sinon-chai#20]
Hello,

After installing and running I get the following error:
![image](https://cloud.githubusercontent.com/assets/4996164/8228260/0ba1b5fe-15b6-11e5-8abd-4b83ee0463b3.png)

By the way, using an older version (with older dependencies) of this project works fine.

**Comment by omerts** [comment]
Ok I found the bug, it is with the endsWith function:
```javascript
var endsWith = function(substr) {
  return function(str) {
    return str.indexOf(substr) === (str.length - substr.length);
  };
};
```
I had a case where str.length - substr.length === -1, and it returned a false positive. 
Wanted to create a pull request, but saw that it is already fixed. 
When will it be deployed?

**Comment by mikechamberlain** [comment]
I am getting a similar error:

    C:\Users\mchambe4\dev\simple\client>node ./node_modules/gulp/bin/gulp.js unit-tests-dev
    [16:29:31] Using gulpfile ~\dev\simple\client\gulpfile.js
    [16:29:31] Starting 'unit-tests-dev'...
    [16:29:31] Starting Karma server...
    WARN [karma]: Port 9876 in use
    INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
    INFO [launcher]: Starting browser PhantomJS
    INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket fMujwCqRPdmidI3BtCYV with id 16821903
    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      ReferenceError: Can't find variable: chai
      at C:/Users/mchambe4/dev/simple/client/node_modules/karma-sinon-chai/node_modules/sinon-chai/lib/sinon-chai.js:17

This works OK on mac, but now I have moved exactly the same setup to Windows, I can no longer run my unit tests.

From that file:

    /* istanbul ignore else */
    if (typeof require === "function" && typeof exports === "object" && typeof module === "object") {
        // NodeJS
        module.exports = sinonChai;
    } else if (typeof define === "function" && define.amd) {
        // AMD
        define(function () {
            return sinonChai;
        });
    } else {
        // Other environment (usually <script> tag): plug in to global chai instance directly.
        chai.use(sinonChai);
    }

I would expect the condition on the first line to return `true` because I am running in Node, but for some reason `module` is not defined.

Any ideas?
