### ISSUE TITLE
lodash version?

### ISSUE THREAD

**Issue by davidbarrows** [kmees/karma-sinon-chai#22]
Hi, sorry if this is a bit OCD but... I'm trying to tidy up my npm dependencies in a project using "npm outdated" and getting the below message; is it possible you could update the lodash version dependency in karma-sinon-chai ?  Just thought I'd ask.  Thank you, -dB

davids-mbp:dBWeb davidwbarrows$ npm outdated
Package       Current  Wanted  Latest  Location
cli-color       0.3.3   0.3.3   1.0.0  cli-color
lodash          2.4.2   2.4.2  3.10.1  lodash
merge-stream    0.1.8   0.1.8   1.0.0  merge-stream
davids-mbp:dBWeb davidwbarrows$ npm update
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb/node_modules/karma-sinon-chai requires lodash@'^2.4.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
lodash@3.10.1 node_modules/lodash

**Comment by kmees** [comment]
Fixed in v1.1.0
