### ISSUE TITLE
Peer dependencies for chai and sinon?

### ISSUE THREAD

**Issue by tilgovi** [kmees/karma-sinon-chai#24]
Might be better to just specify peer dependencies of `*` version for these and let the consumer decide which version to install.

**Comment by jonny-improbable** [comment]
+1; I am using a fork of SinonJS as it [does not play well with webpack](https://github.com/webpack/webpack/issues/304).

**Comment by Jandalf** [comment]
+1

**Comment by ackerdev** [comment]
:+1:

For now you can either override this in your local package.json, or there is the alternative package [karma-chai-sinon](https://www.npmjs.com/package/karma-chai-sinon) which does use peerdeps.

**Comment by brutalcrozt** [comment]
the name `karma-chai-sinon` just give me confusion. IDK why but my expect on jasmine break after use this.
Guys did you think use chai directly is better?

**Comment by joscha** [comment]
I think this can be closed. 866eeaa moved all dependencies to peerDependencies
