### ISSUE TITLE
Getting 'Mismatched anonymous define()'

### ISSUE THREAD

**Issue by loganweiluo** [kmees/karma-sinon-chai#25]
Looks like it's the same issue with https://github.com/kmees/karma-sinon-chai/issues/15, which has been closed.

Still having the same issue with v1.1.0

Error message is:
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
Error: Mismatched anonymous define() module: function () {
return sinonChai;
}
http://requirejs.org/docs/errors.html#mismatch
at /Users/wwluo/work/ctp-mobile/node_modules/requirejs/require.js:140

karma config is: 
frameworks: ['mocha', 'requirejs', 'sinon-chai']

rolling back to v0.2.0 fixes the issue.

**Comment by givankin** [comment]
same issue

**Comment by marcelVII** [comment]
Same problem here ... Any solution yet?

**Comment by givankin** [comment]
@marcelVII I solved it by switching to karma-chai-sinon...
