### ISSUE TITLE
Lolex dependency issue

### ISSUE THREAD

**Issue by timkindberg** [kmees/karma-sinon-chai#26]
I was getting an error on line 69 in sinon-timers.js saying "Can't read property 'install' on undefined". After looking all around, the only thing that worked was this repo that added lolex as a more explicit karma dependency: https://github.com/wombatsecurity/karma-lolex-sinon-chai. 

You might consider merging over their master commits.

**Comment by leftstick** [comment]
Is there any solution for solving this issue?

**Comment by timkindberg** [comment]
Yes, fork that @wombatsecurity repo linked above and use it instead.

This will install from a github repo
```sh
npm i -D YOURNAME/karma-lolex-sinon-chai
``` 

It still works just like regular karma-sinon-chai in terms of how you set up your karma config.

**Comment by helielson** [comment]
+1

**Comment by bricss** [comment]
Seems like something went wrong with **Sinon** versions between 1.12.2 and 1.17.2 (https://github.com/sinonjs/sinon/issues/621)
Can run tests only with `v0.3.0` if I'm trying to update to `v1.1.0` getting same errors as mentioned in https://github.com/kmees/karma-sinon-chai/issues/28

**Comment by kmees** [comment]
Can someone please test [v.1.2.0-rc1](https://github.com/kmees/karma-sinon-chai/tree/v1.2.0-rc1) and report back? Thanks

**Comment by bricss** [comment]
@kmees checked it on alive project and everything works now, all tests a green :relieved:

**Comment by kmees** [comment]
Thanks for testing, will close this issue now.
