### ISSUE TITLE
Cannot find module 'lolex'

### ISSUE THREAD

**Issue by mickaeltr** [kmees/karma-sinon-chai#32]
Hello,

Since I moved my project from 1.1.0 to 1.2.0, I got the following error:

Error: Cannot find module 'lolex'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at framework (/…/node_modules/karma-sinon-chai/index.js:26:40)

**Comment by Malgalad** [comment]
Install `lolex`, `sinon` and `sinon-chai` explicitly and it will work.

**Comment by mickaeltr** [comment]
Shouldn't lolex be a dependency of sinon-chai ?

**Comment by Malgalad** [comment]
In 1.2.0 release all dependencies were moved to peer dependencies. And in npm@3 they are not installed automatically.

**Comment by mickaeltr** [comment]
I see. I really understand why chai, sinon and sinon-chai should be installed explicitly, since they are used in the tests. However that sounds weird to me that a dependency only used by karma-sinon-chai (and mentioned anywhere in the documentation) should be installed explicitly.

**Comment by ptim** [comment]
super helpful, thanks
I needed `chai` as well :)

**Comment by DanPurdy** [comment]
I agree with @mickaeltr here, lolex is required for this package to function and should really come as a dependency, while the other 3 packages are definitely peer dependencies as you are extending their functionality here. Thanks for the package too! :+1:

**Comment by mickaeltr** [comment]
Fixed by https://github.com/kmees/karma-sinon-chai/commit/2af2972f8a70a26ed20abeeab8ed7e73bb23d0e4
Thanks!
