### ISSUE TITLE
npm peerDependencies warning

### ISSUE THREAD

**Issue by lyonlai** [kmees/karma-sinon-chai#33]
npm WARN peerDependencies The peer dependency lolex@^1.4.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sinon-chai@^2.8.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by samithaf** [comment]
Getting the same issue. Would be helpful if we can solve it

**Comment by vinnymac** [comment]
You need to explicitly install `chai`, `sinon`, and `sinon-chai`. You also need to install `lolex` which is unfortunately listed as a peerDepedency and should really be a dependecy.

This was changed in `v1.2.0`.

#32 has more information on this.

**Comment by mickaeltr** [comment]
I think this is now fixed thanks to https://github.com/kmees/karma-sinon-chai/commit/2af2972f8a70a26ed20abeeab8ed7e73bb23d0e4
