### ISSUE TITLE
karma warn: "sinon-timers.js" does not match any file

### ISSUE THREAD

**Issue by icebob** [kmees/karma-sinon-chai#34]
When I run karma I got this warning every time:
```
06 05 2016 13:14:36.016:WARN [watcher]: Pattern "...node_modules\sinon\pkg\sinon-timers.js" does not match any file.
```
I think, the problem is this line: https://github.com/kmees/karma-sinon-chai/blob/master/index.js#L31.
Because in [sinon@1.17.4](https://www.npmjs.com/package/sinon) this file is not exist.

**Comment by adambrunner** [comment]
As of the [changelog](http://sinonjs.org/Changelog.txt), they removed sinon-timers in 1.17.0.]

**Comment by adambrunner** [comment]
@blakef I already sent the pull request for merge, but @kmees doesn't seem to be here for a while to approve and merge it. So it isn't on me now.
