### ISSUE TITLE
No Longer Maintained?

### ISSUE THREAD

**Issue by davezuko** [kmees/karma-sinon-chai#37]
Is this project still being maintained? There are a few critical issues preventing users from using this package successfully, and the PR's seem to be sitting untouched. For the time being, to unblock myself, I have forked this to: https://github.com/davezuko/karma-better-sinon-chai and published it to npm (`npm i karma-better-sinon-chai`). I will gladly deprecate this package if the issues mentioned below get resolved and published; just wanting to help out!

## Fatal Issues
* `lolex` is a dependency but is marked as a `peerDependency`. This means users must install `karma-sinon-chai` and then, after some debugging, realize that they must install it themselves. Futhermore, `peerDependencies` are deprecated in npm3. The relevant [issue](https://github.com/kmees/karma-sinon-chai/issues/32) has been untouched since February.

* `sinon@^1.7.2` no longer includes the `sinon-timers` package, and this is explicitly referenced from `karma-sinon-chai` [here](https://github.com/kmees/karma-sinon-chai/blob/master/index.js#L31). A [PR to fix this](https://github.com/kmees/karma-sinon-chai/pull/35/files) has remained unmerged for over a month.

**Comment by kmees** [comment]
@adambrunner volunteered to undertake the maintenance for the foreseeable future since I currently don't have the time do so.

**Comment by davezuko** [comment]
@kmees thanks for the clarification, and thank you @adambrunner . I will deprecate my fork for the time being.
