### ISSUE TITLE
Possible breakage due to v1.2.3 running karam#start on karma v0.13.x

### ISSUE THREAD

**Issue by travisperson** [kmees/karma-sinon-chai#39]
I have yet to completely confirm this, I'll work up some tests, but I believe the addition of setting the `karma.loaded` is causing some strange issues.

In my tests I now have tons of `TypeError: Cannot read property 'call' of undefined`, as well as half my stubs stopped working. I'll try to pull together some minimal examples to see if it's just the way my tests are written or if this is a breaking change for all of karma v0.13.x.

Karma v0.13.22
Sinon v1.17.4
Chai v3.5.0

Version v1.2.2 of this module works, v1.2.3 works if I comment out the `karma.loaded` code.

**Comment by ruscoder** [comment]
I have the same issue.

**Comment by 4storia** [comment]
Ditto, same problem

**Comment by adambrunner** [comment]
Hi, can you give a little hint, how did it break? I could not reproduce.

**Comment by bankyadam** [comment]
Please test it with latest (`2.0.1`) version and reopen issue if still applies.
