### ISSUE TITLE
peerDependencies are locked

### ISSUE THREAD

**Issue by eddiemonge** [kmees/karma-sinon-chai#43]
peerDependencies should probably be using greater than or equal to. As an example, sinon has a new major version coming out and npm complains since since its not in the same range

**Comment by burnall** [comment]
@adambrunner I see that bumped version are merged into master.
Could advise please, when the new version will be on NPM?
Thanks!

**Comment by tdespenza** [comment]
_You can try using this setting till it's pushed to npm
"karma-sinon-chai": "git+https://github.com/kmees/karma-sinon-chai.git"_

**Comment by DanielPe05** [comment]
@adambrunner Any updates on getting updates to NPM?

**Comment by giggio** [comment]
@tdespenza perfect! I used your suggestion, but added a commit to lock to the commit that updated the dependencies, so I don't get any surprises.

````
"karma-sinon-chai": "git+https://github.com/kmees/karma-sinon-chai.git#bca7e7a2d6e90d4c7c6a6884550c2b3228596d23",
````

And it worked just fine.

**Comment by adambrunner** [comment]
New version is published to npm, thanks for your patience!
