### ISSUE TITLE
karma-sinon-chai package marked as malicious

### ISSUE THREAD

**Issue by JaisHolstein** [kmees/karma-sinon-chai#46]
Hi

In my organisation this package is marked as malicious and cannot be downloaded. Does anyone else have this issue? 

The 'soon to be very grey haired' developer

**Comment by bankyadam** [comment]
Hi, what kind of tools do you use to check packages? I checked it with nsp and no vurnabilities found.

**Comment by JaisHolstein** [comment]
Hi

Looks like it was flagged as malicious in our 'firewall' software. I can now get it using npm. 

Thx
