### ISSUE TITLE
Chai 4.0

### ISSUE THREAD

**Issue by nkovacs** [kmees/karma-sinon-chai#47]
Could you please add support for chai 4.0? Sinon-chai [already supports it](https://github.com/domenic/sinon-chai/commit/40b35f3b60aac5757e231a65f88fa0d8352d2903).

I did a quick test with https://github.com/vuejs-templates/webpack, and it worked fine.

**Comment by kashiif** [comment]
PR #48 fixes this.

**Comment by bankyadam** [comment]
Published as `karma-sinon-chai@1.3.2`
