### ISSUE TITLE
Can't grep individual tests in when running with mocha

### ISSUE THREAD

**Issue by stefan-torstensson** [kmees/karma-sinon-chai#49]
When running with karma and mocha there is an option to execute only specific tests with a grep expression

    karma start
    karma run -- --grep="manager tests"

but this doesn't work when using the karma-sinon-chai plugin since the command line config is lost in the chai-adapter.js.

Replacing the following line in chai-adapter.js
`karma.start();`
with
`karma.start(karma.config);`

makes the mocha adapter pick up the grep argument and only execute the desired tests. Not sure if this is the correct place to fix it, but greping works as expected when the sinon-chai plugin is not included in the karma frameworks config.

**Comment by bankyadam** [comment]
As I see now in the implementation of the karma context (which the `chai-adapter.js` uses), it calls `karma.start()` by passing the `karma.config`, so your suggestion should be correct. I added this in version `2.0.2`.
