### ISSUE TITLE
Updating to sinon ^3.2.0

### ISSUE THREAD

**Issue by DanielPe05** [kmees/karma-sinon-chai#50]
`npm WARN karma-sinon-chai@1.3.2 requires a peer of sinon@^2.1.0 but none was installed.`
Is there any plan to update that peer dependency?

**Comment by eXaminator** [comment]
Any chance of seeing this soon? Is there more to it then updating the package.json? I could create a PR for that, but I'm not sure if there is more to do.

**Comment by HughePaul** [comment]
Sinon 4 is out now

**Comment by JayAndCatchFire** [comment]
This should no longer be an issue.

**Comment by bankyadam** [comment]
I just removed the upper limit for peer dependencies with `2.0.1`.
