### ISSUE TITLE
Mismatched version number in package.json

### ISSUE THREAD

**Issue by JeffryBooher** [kmees/karma-sinon-chai#52]
Support was added for `chai^4.0.0` in #48 but the `version #` in `package.json` wasn't advanced to `1.3.2`; 

`npm` has the correct version stamp `1.3.2` and correct `package.json` but it doesn't match what is in master (https://github.com/kmees/karma-sinon-chai/blob/master/package.json)

**Comment by bankyadam** [comment]
I just removed the upper limit for peer dependencies with `2.0.1`.
