### ISSUE TITLE
support for "sinon": "^4.0.1" missing

### ISSUE THREAD

**Issue by guyulmaz** [kmees/karma-sinon-chai#54]
npm WARN karma-sinon-chai@1.3.2 requires a peer of sinon@^2.1.0 but none is installed. You must install peer dependencies yourself.

I have
"sinon": "^4.0.1",
"chai": "^4.1.2",

**Comment by AlexEvanczuk** [comment]
I was about to open a PR for this... is there any reason why sinon and sinon-chai have such strict versioning?  It doesn't seem to be doing too much with these packages, particularly sinon.  I'm new to this repo, but would it be possible to allow all versions of sinon/chai?

Looks like I don't have permissions to create a pull request, but `package.json` could look something like this:
```javascript
{
  "name": "karma-sinon-chai",
  "description": "Sinon and Chai for Karma",
  "keywords": [
    "karma",
    "chai",
    "sinon",
    "mocha",
    "should"
  ],
  "version": "1.3.1",
  "author": "Kevin Mees <kev.mees@gmail.com>",
  "main": "./index.js",
  "license": "MIT",
  "homepage": "https://github.com/kmees/karma-sinon-chai",
  "repository": {
    "type": "git",
    "url": "https://github.com/kmees/karma-sinon-chai.git"
  },
  "bugs": {
    "url": "https://github.com/kmees/karma-sinon-chai/issues"
  },
  "contributors": [
    "Greg Thornton <xdissent@me.com>",
    "Tobias Kopelke <nox@raynode.de>"
  ],
  "peerDependencies": {
    "chai": "*",
    "sinon": "*",
    "sinon-chai": "*"
  },
  "dependencies": {
    "lolex": "^1.6.0"
  },
  "devDependencies": {}
}
```

Is there any reason why we

**Comment by Kyoss79** [comment]
> Is there any reason why we wouldn't want to do this?
I wouldnt see any reason not to.

**Comment by bankyadam** [comment]
I just removed the upper limit for peer dependencies with `2.0.1`.
