### ISSUE TITLE
Update version of lolex and/or make it optional?

### ISSUE THREAD

**Issue by JayAndCatchFire** [kmees/karma-sinon-chai#57]
While I did https://github.com/kmees/karma-sinon-chai/pull/56, I noticed that the lolex dependency is still on version 1.6.0 while lolex is now on 2.3.2.  Also, looking at the `index.js` in this package, it looks like it doesn't _use_ lolex so much as provide it.  I've personally never _needed_ lolex.  Wouldn't it be nice if lolex was an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies)?  That way, people can bring whatever version of lolex they want.  Just a thought.

Let me know if that's something you'd be into supporting.  I'd be happy to make a PR.

**Comment by bankyadam** [comment]
I'd recommend to remove lolex from the package and try to push users to use [Sinon.js fake timers](http://sinonjs.org/releases/v4.5.0/fake-timers/). This would require a major release update.

**Comment by JayAndCatchFire** [comment]
@bankyadam https://github.com/kmees/karma-sinon-chai/pull/58

**Comment by bankyadam** [comment]
Published as `2.0.0`
